# Rakefile

task :default => ["run_all_tests"]

desc "Run test suite"
task :run_all_tests do
  # think about how to set up a testing environment here?
  # set environment to 'test' before requiring sinatra gem
  # ENV['RACK_ENV'] = 'test'
  # require ('sinatra')
  # reset test database
  # run test files
  ruby '../db/santa_test_seeds.rb'

  ruby 'team_spec.rb'
  # add other test file names here
end

# Rakefile
